"""domain

Revision ID: e0d7e4726542
Revises: b377fd9a441f
Create Date: 2020-02-16 01:21:31.102866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0d7e4726542'
down_revision = 'b377fd9a441f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service', sa.Column('domain', sa.String(length=16), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service', 'domain')
    # ### end Alembic commands ###
